// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rel2CodeFirst.Models;

#nullable disable

namespace Rel2CodeFirst.Migrations
{
    [DbContext(typeof(CompanyContextCF))]
    partial class CompanyContextCFModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Rel2CodeFirst.Models.Dept", b =>
                {
                    b.Property<int>("Deptno")
                        .HasColumnType("int");

                    b.Property<string>("Deptname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Deptno");

                    b.ToTable("Depts");
                });

            modelBuilder.Entity("Rel2CodeFirst.Models.Emp", b =>
                {
                    b.Property<int>("EmpNo")
                        .HasColumnType("int");

                    b.Property<int?>("DeptnavDeptno")
                        .HasColumnType("int");

                    b.Property<string>("EmpName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("deptno")
                        .HasColumnType("int");

                    b.HasKey("EmpNo");

                    b.HasIndex("DeptnavDeptno");

                    b.ToTable("emps");
                });

            modelBuilder.Entity("Rel2CodeFirst.Models.Emp", b =>
                {
                    b.HasOne("Rel2CodeFirst.Models.Dept", "Deptnav")
                        .WithMany("Emps")
                        .HasForeignKey("DeptnavDeptno");

                    b.Navigation("Deptnav");
                });

            modelBuilder.Entity("Rel2CodeFirst.Models.Dept", b =>
                {
                    b.Navigation("Emps");
                });
#pragma warning restore 612, 618
        }
    }
}
